### ISSUE TITLE
"Ready" packet won't get sent when the game is started.

### ISSUE THREAD

**Issue by edqx** [kognise/among-js#5]

**Comment by cybershard** [comment]
**This is a really big issue**. Some steps to reproduce are 
- Run official Among Us Client, and create a room
- Run among-js and join a room
- Host presses start game once there is enough people
- The among-js client does not send "ready" packet like the official client, or other client implementations. 

This error prevents the among-js client from loading into a game, and breaks the client. I can create a patch to fix this, let me know if PRs are accepted.

**Comment by edqx** [comment]
I've been looking around the last few hours at the codebase but I can't find a single Ready packet. I think this must be an issue with the vanilla client, I asked Bill Gates and he was completely stumped. I think the next step is to decompile the beta and see if anything has changed, let me know if you find anything.

**Comment by kognise** [comment]
@cybershard PRs are accepted although I'm probably perfectly capable of fixing this myself!

I wouldn't wish anyone else to spend hours trying to fix this really convoluted and difficult-to-solve problem.

**Comment by edqx** [comment]
I think this is safe to be closed with 68ff58f, we praise you for your hard work, Kognise.
